# Setup
title:               Srikanth Sastry
tagline:             'A Techie in Boston'
description:         'A personal website'
url:                 '//srikanth.sastry.name'
baseurl:             ''
paginate:            5
permalink:           /:slug/

# About/contact
author:
  name:              Srikanth Sastry
  url:               '//srikanth.sastry.name'
  email:             srikanth@sastry.name

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
