# Setup
title:               Srikanth Sastry
tagline:             'A Techie in Boston'
description:         'A personal website'
url:                 https://srikanthsastry.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Srikanth Sastry
  url:               https://srikanthsastry.github.io
  email:             srikanth@sastry.name

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
